name: smart-subscription

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download + Merge
        run: |
          mkdir output
          touch output/raw.txt

          while read url; do
            echo "Fetching $url"
            curl -s --max-time 15 "$url" >> output/raw.txt
            echo "" >> output/raw.txt
          done < sources.txt

      - name: Clean (remove duplicates)
        run: |
          sort output/raw.txt | uniq > output/clean.txt

      - name: Encode to base64 subscription
        run: |
          base64 -w 0 output/clean.txt > output/sub.txt

      - name: Create subscription file
        run: |
          echo "data:text/plain;base64," > output/link.txt
          cat output/sub.txt >> output/link.txt

      - name: Upload subscription
        uses: actions/upload-artifact@v4
        with:
          name: subscription
          path: output/link.txt
