name: merge-subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build file
        run: |
          mkdir public
          > public/sub.txt

          while read url; do
            echo "Fetching $url"
            curl -s --max-time 15 "$url" >> public/sub.txt
            echo "" >> public/sub.txt
          done < sources.txt

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
