name: auto-subscription

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download + Merge + Clean
        run: |
          mkdir output
          touch output/all.txt

          while read url; do
            echo "Fetching $url"
            curl -s --max-time 15 "$url" >> output/all.txt
            echo "" >> output/all.txt
          done < sources.txt

          sort output/all.txt | uniq > output/clean.txt

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: subscription
          path: output/clean.txt
